# Generated by Django 4.0.5 on 2025-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.URLField(max_length=50, unique=True)),
                ('category_image', models.ImageField(upload_to='photos/categories')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
